apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: shared-pvc
spec:
  accessModes:
    - ReadWriteMany # PV의 Access Mode와 일치
  resources:
    requests:
      storage: 1Gi
  storageClassName: "" # StorageClass를 명시하지 않음 (PV와 일치하도록)
